export const tailwindStyles = {
  btn: [
    "w-full",
    "px-6",
    "py-2.5",
    "bg-blue-600",
    "text-white",
    "leading-tight",
    "rounded",
    "shadow-md",
    "over:bg-blue-700",
    "hover:shadow-lg",
    "focus:bg-blue-700",
    "focus:shadow-lg",
    "focus:outline-none",
    "focus:ring-0",
    "active:bg-blue-800",
    "active:shadow-lg",
    "transition duration-150",
    "ease-in-out",
  ].join(" "),

  table: [
    "flex",
    "flex-col",
    "overflow",
    "overflow-x-auto",
    "sm:-mx-6",
    "lg:-mx-8",
    "py-2",
    "inline-block",
    "min-w-full",
    "sm:px-6",
    "lg:px-8",
    "overflow-hidden",
  ].join(""),

  formItem: [
    "form-control",
    "block",
    "w-full",
    "px-5",
    "py-2",
    "text-base",
    "text-normal",
    "border",
    "border-solid",
    "border-gray-300",
    "rounded",
    "transition",
    "ease-in-out",
    "focus:border-blue-600",
    "focus:outline-none",
  ].join(" "),
};
